services:
  # app:
  #   build: .
  #   command: 'bash -c "sqlx db setup && cargo run"'
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/app-db
  db:
    image: "postgres:14.0"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  .:

